Create function to enable (automatic) GPG signing on a repo

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -166,6 +166,44 @@ function docker_rm_last() {
     echo "Done"
 }
 
+# Enable GPG signing for a repository
+#
+# First, this function sets the GPG key to use for signing commits,
+# based on the given signature.
+#
+# Then, this function enables automatic signing for commits,
+# so the flag -S doesn't have to be supplied when committing.
+#
+# $1: ID of the GPG key to use
+function git_enable_gpg() {
+    # Make sure a key is entered
+    if [[ ! "$1" ]]; then
+        echo "Please provide a GPG key ID!"
+        echo "  git_enable_gpg [GPG_ID]"
+        return 1
+    fi
+
+    # List the key by it's ID
+    echo "Checking the GPG key ID..."
+    gpg --list-keys $1
+
+    # Report, return if the key is invalid
+    if [[ ! $? -eq 0 ]]; then
+        echo "Invalid GPG key ID!"
+        return 1
+    fi
+
+    echo "Enabling GPG signing..."
+
+    # Set the signing key
+    git config user.signingKey $1
+
+    # Enable signing by default
+    git config commit.gpgsign true
+
+    echo "Done"
+}
+
 # Set the preferred editor
 export EDITOR=vim
 
